// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgID.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from msgID.proto</summary>
  public static partial class MsgIDReflection {

    #region Descriptor
    /// <summary>File descriptor for msgID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgttc2dJRC5wcm90bxIIcHJvdG9jb2wqwQEKA01TRxIMCghNU0dfTk9ORRAA",
            "EhYKEUMyU19Mb2dpbl9SZXFfTVNHEOkHEhYKEVMyQ19Mb2dpbl9SZXNfTVNH",
            "EOoHEhwKF0MyU19DcmVhdGVfUm9sZV9SZXFfTVNHENEPEhwKF1MyQ19DcmVh",
            "dGVfUm9sZV9SZXNfTVNHENIPEh8KGkMyU19Sb2xlX0hlYXJ0YmVhdF9SZXFf",
            "TVNHENMPEh8KGlMyQ19Sb2xlX0hlYXJ0YmVhdF9SZXNfTVNHENQPYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MSG), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MSG {
    [pbr::OriginalName("MSG_NONE")] None = 0,
    /// <summary>
    ///登录
    /// </summary>
    [pbr::OriginalName("C2S_Login_Req_MSG")] C2SLoginReqMsg = 1001,
    /// <summary>
    ///登录返回
    /// </summary>
    [pbr::OriginalName("S2C_Login_Res_MSG")] S2CLoginResMsg = 1002,
    /// <summary>
    ///创建角色
    /// </summary>
    [pbr::OriginalName("C2S_Create_Role_Req_MSG")] C2SCreateRoleReqMsg = 2001,
    /// <summary>
    ///创建角色返回
    /// </summary>
    [pbr::OriginalName("S2C_Create_Role_Res_MSG")] S2CCreateRoleResMsg = 2002,
    /// <summary>
    ///角色心跳
    /// </summary>
    [pbr::OriginalName("C2S_Role_Heartbeat_Req_MSG")] C2SRoleHeartbeatReqMsg = 2003,
    /// <summary>
    ///角色心跳返回
    /// </summary>
    [pbr::OriginalName("S2C_Role_Heartbeat_Res_MSG")] S2CRoleHeartbeatResMsg = 2004,
  }

  #endregion

}

#endregion Designer generated code
